### PR TITLE
Fix events not triggered

### PR DESCRIPTION
**Pull request by spondbob**
Fixes:
- Initialised `events` from `options` instead of `config`.
- Webpack outputs module into `dist/dist` instead of `dist`.

### CODE REVIEW

**Comment by spondbob** [comment]
I just realised after changing webpack's output, sometimes the modules are created under project's root folder but other times inside `dist/dist`. I might have wrong with the config, may need to adjust it again.

**Comment by pratikt-cuelogic** [comment]
@stefanneculai , can we merge this if its good to go ?

**Comment by stefanneculai** [comment]
I am not sure if there is any specific reason for this change. That is why it was not being merged up to now.

**Comment by spondbob** [comment]
To me the main point was events not triggered because it was looking at different props. [This doc](https://github.com/froala/react-froala-wysiwyg#events-and-methods) says it uses `options.events` while [the code](https://github.com/froala/react-froala-wysiwyg/pull/93/files#diff-21d9ff32c22a8353d841ed7810bde770L233) is looking at `config.events`.

I don't know which one is the correct design or I might have misinterpret it, but I never have my events triggered by checking out the code from this repo.

**Pull request closed without merging**
