### PR TITLE
Use 'create-react-class' package instead of React.createClass

### LINKED ISSUE #23: Use 'create-react-class' package instead of React.createClass
`React.createClass` has been deprecated and extracted to it's own package since [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings).

The following warning is displayed if that version of React is used:
`Warning: FroalaEditor: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

See [Migrating from `React.createClass`](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass) to fix this.

This could be a temporary fix, but I think moving to ES6 classes is more appropriate :-)

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #23

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@stefanneculai I think this can be merged isn't it?

**Comment by stefanneculai** [comment]
@MichaelDeBoey we're going to review it by the end of the week.

**Comment by MichaelDeBoey** [comment]
OK thanks :-)
Right now I only migrated to the new `create-react-class` package, but I can write a migration to ES6 classes to if you guys want?

**Comment by stefanneculai** [comment]
That would really handy. Thanks a million!

**Comment by MichaelDeBoey** [comment]
Will take a look at it this evening, but I think this can be merged already for now :-)

**Comment by MichaelDeBoey** [comment]
@stefanneculai Any news on this one? :-)

**Comment by MichaelDeBoey** [comment]
Thanks for merging this one @stefanneculai! :-)
Any idea when the new release is coming?

I'll make a new issue + PR for the ES6 classes btw :-)

**Comment by stefanneculai** [comment]
This week.

**Comment by MichaelDeBoey** [comment]
@stefanneculai Any news on the new release?

**Comment by stefanneculai** [comment]
Today :)

**Comment by stefanneculai** [comment]
@MichaelDeBoey published on npm 😃

**Comment by MichaelDeBoey** [comment]
@stefanneculai Thanks! :-)

**Comment by MichaelDeBoey** [comment]
@stefanneculai I get the following error: `Uncaught Error: Cannot find module "create-react-class"`

**Comment by stefanneculai** [comment]
Please try again now. You should get version `2.6.0-1`

**Pull request merged**
