### PR TITLE
Support React 17

### PR DESCRIPTION
**Pull request by jorgenschaefer**
React 17 has been out since October last year. It seems react-froala-wysiwyg does not need any updates to just work with it. Would it be possible to add it to the peerDependencies so we can upgrade without conflicts? :-)

### CODE REVIEW

**Review by tomsturge — APPROVED** [review]

**Comment by tomsturge** [comment]
This would be amazing. Means we can remove the `--force` flag from our `npm i` process

**Comment by mephju** [comment]
@jorgenschaefer  let's merge it :)

**Comment by jorgenschaefer** [comment]
@mephju Sounds great. Can I do anything to make that happen?

**Review by mephju — APPROVED** [review]

**Comment by mephju** [comment]
@jorgenschaefer  I just realized that i can approve it. So it's approved. Maybe you can merge it now?!

**Comment by jorgenschaefer** [comment]
@mephju I do not have write access to this repo, you will have to merge this yourself I'm afraid.

**Comment by mephju** [comment]
I can't. I'm just a random guy on the internet.
@tomsturge  What's holding us back?

**Comment by mephju** [comment]
@kapil2704 any thoughts?

**Comment by jorgenschaefer** [comment]
> I can't. I'm just a random guy on the internet.

Great. Me too :-D

**Comment by kapil2704** [comment]
@mephju you are right

**Comment by mephju** [comment]
@kapil2704  thanks :)

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by mephju** [comment]
@kapil2704 i think this should get a patch version bump and be re-released to npm

**Pull request merged**
