### PR TITLE
Change refs from static to callback refs

### PR DESCRIPTION
**Pull request by CMatias**
In the process of integrating Froala with [Strapi](https://strapi.io/) I was getting the [following error](https://reactjs.org/docs/error-decoder.html/?invariant=290&args[]=el) when running a production build:

```
Element ref was specified as a string (el) but no owner was set. 
This could happen for one of the following reasons: 
1. You may be adding a ref to a function component 
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded See https://fb.me/react-refs-must-have-owner for more information.
```

I saw that Froala used string refs (`ref='el'`) which is a [legacy api](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) of setting refs in React.

I've updated the way refs are handled and the production build was able to work. I've tested the demo and it also works as intended. Is there anything more I should test with?

Strapi deps:
```
 "strapi": "3.0.0-alpha.26.1",
 "react": "^16.8.4",
```

### CODE REVIEW

**Comment by lukaszwnek** [comment]
Hi @CMatias, we've just run into the same issue - thanks for identifying it and the fix! Would you mind sharing the status of this PR?

**Comment by CMatias** [comment]
Not sure I can give you answer about the status @lukaszwnek , it's still open. If there's an interest to merge this I'll gladly merge the new changes and resolve the conflicts.

**Comment by lukaszwnek** [comment]
@stefanneculai @navneetnagpal Could you guys please chime in? Is that a change you'd be interested in merging?

**Comment by navneetnagpal** [comment]
@CMatias Thanks for the changes.
All changes related to to refs are looking good. However can you do few more changes below
1) resolve all the conflicts
2) revert the lib/FroalaEditorFunctionality.jsx 
3) raise 2 prs one for master having 3.0.0-rc.1 version second for v2 branch having 2.9.5 version of froala.

Thanks in advance,
Navneet

**Comment by navneetnagpal** [comment]
@CMatias we have merged for both versions in separate PR(s)
Thank you @CMatias for the changes,
Navneet

**Comment by CMatias** [comment]
Hey @navneetnagpal, thanks for doing the changes. I had this in my todo but hand't find the time yet. Cheers!

**Pull request closed without merging**
